name: my3d_linux
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    # -------- 核心 3D / 渲染 --------
    - vtk==9.6.0
    - pyvista==0.47.0
    - pyvistaqt==0.11.3
    - open3d==0.10.0
    # -------- UI --------
    - PySide6==6.10.2
    - QtPy==2.4.3
    # -------- 科学计算 --------
    - numpy>=1.24,<2.0
    - scipy==1.15.2
    - scikit-learn==1.7.2
    - matplotlib>=3.7
    # -------- 其他依赖 --------
    - PyYAML==6.0.2
    - pywin32==311; sys_platform == 'win32'
